name: deploy-to-kubernetes.yaml

on:
  push:
    branches: [main]
    # paths: .github/workflows/deploy-to-kubernetes.yaml
  pull_request:
    branches: none

  workflow_dispatch:

# env:
#   TOKEN: ${{ secrets.}}

jobs:
  deploy-app-to-kubernetes:
    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Set release version
      run: echo "RELEASE_VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - id: lower-repo
      run: |
        echo "IMAGE=${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: |
          ghcr.io/${{env.IMAGE}}:${{ env.RELEASE_VERSION }}
        secrets: "github_token=${{ secrets.GITHUB_TOKEN }}        \n"
        # cache-from: type=gha
        # cache-to: type=gha,mode=max
